spring:
  data:
    redis:
      host: 192.168.31.140
      port: 6379
  rabbitmq:
    host: 192.168.31.140
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 5
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2
        default-requeue-rejected: false