server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  application:
    name: mall-auth
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  cache:
    redis:
      time-to-live: 180000
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.140:8848
        namespace: 6e152ee2-97b5-461d-aa45-32f1fb13a5ca
        group: DEFAULT_GROUP
  # ==================== 邮件配置 ====================
  mail:
    default-encoding:
    host: smtp.qq.com
    port: 587
    username: 2265534937@qq.com
    password: xwypdgkcdnmdeade
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: health,info