# 开发环境配置
# Nacos 与 Redis 地址指向虚拟机

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.140:8848
        namespace: 6e152ee2-97b5-461d-aa45-32f1fb13a5ca
  data:
    redis:
      host: 192.168.31.140
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4
          max-wait: 3000ms