server:
  port: 8084
  servlet:
    context-path: /api

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  application:
    name: mall-product
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

# Elasticsearch 配置
elasticsearch:
  host: 192.168.31.140
  port: 9200
  index: mall_spu

# 文件上传配置
file:
  upload:
    base-path: ./uploads

# ==================== Feign 熔断降级（使用 Sentinel） ====================
feign:
  circuitbreaker:
    enabled: true

# Feign 日志级别
logging:
  level:
    com.cyh.mallproduct.feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"